pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Checkout Code') {
            steps {
                // Use the SCM settings from the Jenkins job configuration
                checkout scm
                sh 'ls -la'
            }
    }
    stage('Install package') {
      steps {
        dir('app') { // Navigate to the directory where package.json is located
          sh 'npm install'
        }
      }
    }

    stage('run app') {
      steps {
        dir('app') { // Ensure we are in the correct directory
          sh 'npm run start'
        }
      }
    }
  }
}
