pipeline {
  agent {
    docker { 
      image 'node:16-alpine' 
      args '-u 111:113' 
      }
  }
  stages {
    stage('Checkout Code') {
            steps {
                // Use the SCM settings from the Jenkins job configuration
                checkout scm
                sh 'ls -la'
            }
    }
    stage('Install package') {
      steps {
        dir('my-first-pipeline') { // Navigate to the directory where package.json is located
          sh  'npm config set cache $(pwd)/.npm-cache --global && npm install'
        }
      }
    }

    stage('run app') {
      steps {
        dir('my-first-pipeline') { // Ensure we are in the correct directory
          sh 'npm run start'
        }
      }
    }
  }
}
